[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[site]
  name = "MAVRIDIS - Constructions & Architectural Services"
  description = "MAVRIDIS - Constructions & Architectural Services"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200